//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToDoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToDoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDo.Resources.ToDoResources", typeof(ToDoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit option selected.
        /// </summary>
        internal static string Menu_Caption_FinishApp {
            get {
                return ResourceManager.GetString("Menu_Caption_FinishApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the option to perform: .
        /// </summary>
        internal static string Menu_Caption_Title {
            get {
                return ResourceManager.GetString("Menu_Caption_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a valid option.
        /// </summary>
        internal static string Menu_Error_InvalidOption {
            get {
                return ResourceManager.GetString("Menu_Error_InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Exit.
        /// </summary>
        internal static string Menu_Option_Exit {
            get {
                return ResourceManager.GetString("Menu_Option_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. New task.
        /// </summary>
        internal static string Menu_Option_NewTask {
            get {
                return ResourceManager.GetString("Menu_Option_NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Pending tasks.
        /// </summary>
        internal static string Menu_Option_PendingTasks {
            get {
                return ResourceManager.GetString("Menu_Option_PendingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Remove task.
        /// </summary>
        internal static string Menu_Option_RemoveTask {
            get {
                return ResourceManager.GetString("Menu_Option_RemoveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task registered successfully.
        /// </summary>
        internal static string NewTask_Caption_Success {
            get {
                return ResourceManager.GetString("NewTask_Caption_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the task:.
        /// </summary>
        internal static string NewTask_Caption_Title {
            get {
                return ResourceManager.GetString("NewTask_Caption_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while registering new task. Try again or contact support.
        /// </summary>
        internal static string NewTask_Error_Exception {
            get {
                return ResourceManager.GetString("NewTask_Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a task name.
        /// </summary>
        internal static string NewTask_Error_InvalidTaskName {
            get {
                return ResourceManager.GetString("NewTask_Error_InvalidTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}.
        /// </summary>
        internal static string PendingTasks_Caption_IndexTask {
            get {
                return ResourceManager.GetString("PendingTasks_Caption_IndexTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while listing tasks. Try again or contact support.
        /// </summary>
        internal static string PendingTasks_Error_Exception {
            get {
                return ResourceManager.GetString("PendingTasks_Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not tasks to perform.
        /// </summary>
        internal static string PendingTasks_Error_NotTasks {
            get {
                return ResourceManager.GetString("PendingTasks_Error_NotTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}.
        /// </summary>
        internal static string RemoveTask_Caption_IndexTask {
            get {
                return ResourceManager.GetString("RemoveTask_Caption_IndexTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} deleted.
        /// </summary>
        internal static string RemoveTask_Caption_Success {
            get {
                return ResourceManager.GetString("RemoveTask_Caption_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of the task to remove:.
        /// </summary>
        internal static string RemoveTask_Caption_Title {
            get {
                return ResourceManager.GetString("RemoveTask_Caption_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while removing task. Try again or contact support.
        /// </summary>
        internal static string RemoveTask_Error_Exception {
            get {
                return ResourceManager.GetString("RemoveTask_Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter a valid number.
        /// </summary>
        internal static string RemoveTask_Error_InvalidNumber {
            get {
                return ResourceManager.GetString("RemoveTask_Error_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not tasks to be removed.
        /// </summary>
        internal static string RemoveTask_Error_NotTasks {
            get {
                return ResourceManager.GetString("RemoveTask_Error_NotTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task number ({0}) does not exist.
        /// </summary>
        internal static string RemoveTask_Error_TaskNotFound {
            get {
                return ResourceManager.GetString("RemoveTask_Error_TaskNotFound", resourceCulture);
            }
        }
    }
}
